language: python
python:
  - "3.8"

install:
  - make django-setup-dev

jobs:
  include:
    - stage: Django code convention
      script:
        - make django-code-convention
    - stage: Django typing checker
      script:
        - make django-typing-checker
    - stage: Django security checker
      script:
        - make django-security-checker
    - stage: Django test
      script:
        - make django-test
      on:
        branch: master

after_success:
  - coveralls