language: python
python:
  - "3.8"

install:
  - make django-setup-dev

jobs:
  include:
    #- stage: Django code convention
    #  script:
    #    - make django-code-convention
    #- stage: Django typing checker
    #  script:
    #    - make django-typing-checker
    #- stage: Django security checker
    #  script:
    #    - make django-security-checker
    - stage: Django test
      script:
        - pytest --nomigrations --cov-report=term-missing  --cov-report=xml --cov-report=annotate --cov=. --disable-warnings
      after_success:
        - coveralls --verbose
