version: "3.7"

services:
  django:
    container_name: django
    build:
      context: ./django
      dockerfile: Dockerfile.production
    expose:
      - 8000
    env_file:
      - ./django/.env
    command: gunicorn bolsonaro_api.wsgi:application --workers=3 --bind=:8000 --max-requests=1000 --max-requests-jitter=50
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  #react:
  #  container_name: react
  #  build:
  #    context: ./react
  #    dockerfile: Dockerfile.production
  #  volumes:
  #    - react_static_volume:/app/react/build/static
  #  expose:
  #    - 3000
  #  env_file:
  #    - ./react/.env
  #  command: serve --single build --listen=3000
  #  depends_on:
  #    - django

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    #volumes:
    #  - react_static_volume:/app/react/react_files/static
    ports:
      - 80:80
    depends_on:
      #  - react
      - django
    environment:
      - NGINX_SERVER=django
      - DJANGO_PORT=8000

volumes:
  postgres_data:
  #react_static_volume:
