version: "3.7"

services:
  django:
    container_name: django
    build:
      context: ./django
      dockerfile: Dockerfile.local
    volumes:
      - ./django:/app/django
    ports:
      - 8000:8000

  react:
    container_name: react
    build:
      context: ./react
      dockerfile: Dockerfile.local
    volumes:
      - ./react:/app/react
      - /app/react/node_modules
    ports:
      - 3000:3000
    depends_on:
      - django
