version: "3.7"

services:
  django:
    container_name: django
    image: muriloscarpasitonio/bolsonaro-api:django
    volumes:
      - django_static_volume:/app/django/static
    expose:
      - 8000
    env_file:
      - ./django/.env
    command: gunicorn bolsonaro_api.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env

  react:
    container_name: react
    image: muriloscarpasitonio/bolsonaro-api:react
    volumes:
      - react_static_volume:/app/react/build/static
    expose:
      - 3000
    env_file:
      - ./react/.env
    command: serve -s build -l 3000
    depends_on:
      - django

  nginx:
    container_name: nginx
    restart: always
    image: muriloscarpasitonio/bolsonaro-api:nginx
    volumes:
      - django_static_volume:/app/django/django_files/static
      - react_static_volume:/app/react/react_files/static
    ports:
      - 80:80
    depends_on:
      - react

volumes:
  postgres_data:
  django_static_volume:
  react_static_volume:
