version: "3.7"

services:
  django:
    container_name: django
    build:
      context: ./django
      dockerfile: Dockerfile.local
    volumes:
      - ./django:/app/django
    ports: 
      - 8000:8000
    env_file:
      - ./django/.env

  react:
    container_name: react
    build:
      context: ./react
      dockerfile: Dockerfile.local
    volumes:
      - ./react:/app/react
      - /app/react/node_modules
    ports: 
      - 3000:3000
    env_file:
      - ./react/.env
    depends_on:
      - django
    