fmt:
	docker-compose run --rm terraform fmt -recursive

init:
	docker-compose run --rm terraform init

validate:
	docker-compose run --rm terraform validate

plan:
	docker-compose run --rm terraform plan

apply:
	docker-compose run --rm terraform apply

destroy:
	docker-compose run --rm terraform destroy