FROM python:3.9-alpine

RUN apk add --update --no-cache --virtual .tmp-build-deps gcc libc-dev linux-headers

COPY ./requirements ./requirements
RUN pip install -r requirements/local.txt
RUN apk del .tmp-build-deps

WORKDIR /app/django

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
