FROM python:3.9-alpine

ENV PYTHONUNBUFFERED=1

RUN apk add --update --no-cache --virtual .tmp-build-deps gcc libc-dev linux-headers

COPY ./requirements ./requirements
RUN pip install -r requirements/local.txt
RUN apk del .tmp-build-deps

WORKDIR /app/django

COPY ./entrypoint.local.sh /app/django/entrypoint.local.sh

RUN chmod +x /app/django/entrypoint.local.sh
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
