FROM python:3.9-buster

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends build-essential gcc

WORKDIR /app/django

COPY ./requirements ./requirements
RUN pip install -r requirements/local.txt

COPY ./entrypoint.local.sh /app/django/entrypoint.local.sh

RUN chmod +x /app/django/entrypoint.local.sh
ENTRYPOINT ["/app/django/entrypoint.local.sh"]
