# Generated by Django 3.1.5 on 2021-01-18 19:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('source', models.CharField(max_length=1000, validators=[django.core.validators.URLValidator(message='URL inválido')], verbose_name='Fonte')),
                ('date', models.DateField(verbose_name='Data da ação')),
                ('date_is_estimated', models.BooleanField(default=False, verbose_name='A data é estimada?')),
                ('additional_infos', models.TextField(blank=True, verbose_name='Informações adicionais')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
            },
        ),
        migrations.CreateModel(
            name='ActionTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='actions.actiontags')),
            ],
            options={
                'verbose_name': 'Marcador de ação',
                'verbose_name_plural': 'Marcadores de ações',
            },
        ),
        migrations.CreateModel(
            name='TaggedAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_taggedaction_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_taggedaction_items', to='actions.actiontags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionSuggestionChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('source', models.CharField(max_length=1000, validators=[django.core.validators.URLValidator(message='URL inválido')], verbose_name='Fonte')),
                ('date', models.DateField(verbose_name='Data da ação')),
                ('date_is_estimated', models.BooleanField(default=False, verbose_name='A data é estimada?')),
                ('additional_infos', models.TextField(blank=True, verbose_name='Informações adicionais')),
                ('user_email', models.EmailField(max_length=254, verbose_name='E-mail do usuário')),
                ('justification', models.TextField(verbose_name='Justificativa da mudança')),
                ('original_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.action')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='actions.TaggedAction', to='actions.ActionTags', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Sugestão de mudanças em ação',
                'verbose_name_plural': 'Sugestões de mudanças em ações',
            },
        ),
        migrations.CreateModel(
            name='ActionSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('source', models.CharField(max_length=1000, validators=[django.core.validators.URLValidator(message='URL inválido')], verbose_name='Fonte')),
                ('date', models.DateField(verbose_name='Data da ação')),
                ('date_is_estimated', models.BooleanField(default=False, verbose_name='A data é estimada?')),
                ('additional_infos', models.TextField(blank=True, verbose_name='Informações adicionais')),
                ('user_email', models.EmailField(max_length=254, verbose_name='E-mail do usuário')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='actions.TaggedAction', to='actions.ActionTags', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Sugestão de ação',
                'verbose_name_plural': 'Sugestões de ações',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='actions.TaggedAction', to='actions.ActionTags', verbose_name='Tags'),
        ),
    ]
